pipeline {
    agent any
    tools {
        jdk 'jdk11'
        maven 'maven'   
    }   
    stages {
        stage('test java installation') {
            steps {
                sh 'java -version'                          
            }       
        }       
        stage('test maven installation') {
            steps {
                sh 'mvn -version'                      
            }       
        }
        stage('Install') {
            steps {  
                dir('./lab4/Ex1/gs-employee-mngr'){             
                    sh "pwd"
                    sh "mvn clean install"          
                } 
            }           
            post {               
                always {                   
                    junit '**/target/*-reports/TEST-*.xml'              
                }           
            }       
        }  
    } 
}
